---
AWSTemplateFormatVersion: '2010-09-09'
Description: A static website with contact form. S3, Cloud Formation, Lambda, SES.
Parameters:
  ParamS3Bucket:
    Default: www.somewebsite.example
    Description: S3 bucket to contian the website
    Type: String
    MinLength: 3
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref ParamS3Bucket
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
    DeletionPolicy: Retain
  LambdaContactFormSendEmail:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        ZipFile: !Sub |
          console.log("WARNING. This function needs to be replaced by the second dpart of the deploy!")
      Description: Send an email in response to a completed contact form
      FunctionName: cloudformation-contact-form-send-email
      Handler: index.handler
      MemorySize: 256
      Role:
        Fn::GetAtt:
        - LambdaExecutionRole
        - Arn
      Runtime: nodejs14.x
      Timeout: 1
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      Policies:
      - PolicyName: root
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - logs:*
            Resource: arn:aws:logs:*:*:*
          - Effect: Allow
            Action:
            - "ec2:CreateNetworkInterface"
            - "ec2:DescribeNetworkInterfaces"
            - "ec2:DeleteNetworkInterface"
            Resource: "*"